# by @dfleta
version: "3.8"

services: 
    db:
        image: mariadb:latest
        container_name: maria_app
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: <db_name>
            MARIADB_USER: developer
            MARIADB_PASSWORD: developer
        ports:
            - 3306:3306
        networks:
            backend: 
                aliases: 
                    - db
    api:
        build:
            context: .
            dockerfile: ./src/main/docker/Dockerfile.jvm
        image: <api_name>:dev
        container_name: <api_name>-api-dev
        depends_on: 
            - db
        ports: 
            - 8080:8080
        networks: 
            - backend
networks:
    backend:
        name: network-backend
        driver: bridge
